# Generated by Django 3.0.5 on 2020-04-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'band',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='playlist.Band')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albuns', to='playlist.Band')),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, related_name='musics', to='playlist.Album'),
            preserve_default=False,
        ),
    ]
